image: Visual Studio 2019

environment:
  JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

build_script:
  - set JAVA_HOME="C:\Program Files (x86)\Java\jdk1.8.0"
  - gradlew :core:cmake --info --stacktrace --no-daemon
  - set JAVA_HOME="C:\Program Files\Java\jdk1.8.0"
  - gradlew :core:cmakeWin64 --info --stacktrace --no-daemon
  - gradlew jar

cache:
  - C:\Users\appveyor\.gradle

test_script:
  - set JAVA_HOME="C:\Program Files\Java\jdk1.8.0"
  - gradlew test --info --stacktrace --no-daemon
  - set JAVA_HOME="C:\Program Files (x86)\Java\jdk1.8.0"
  - gradlew test --info --stacktrace --no-daemon

artifacts:
  - path: 'core\build\libs\*.jar'
    name: jimgui-core
  - path: 'kotlin-dsl\build\libs\*.jar'
    name: jimgui-dsl
  - path: 'fun\build\libs\*.jar'
    name: jimgui-fun
#
