# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      PATH: "~/.yarn/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

    steps:
      - checkout

      - run:
          name: Install clang, make, glfw3, pkg-config
          command: |
            sudo apt-get update
            sudo apt-get install -y make libglfw3-dev libglfw3-dev pkg-config gcc g++
            gcc -v

      - run:
          name: Install cmake
          command: |
            mkdir -p cmake-3.14
            wget -qO- "https://cmake.org/files/v3.14/cmake-3.14.3-Linux-x86_64.tar.gz" | tar --strip-components=1 -xz -C cmake-3.14

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle.kts" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: bash gradlew dependencies --no-daemon

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-

      - run:
          name: Build all projects
          command: PATH=`pwd`/cmake-3.14/bin:$PATH bash gradlew jar --info --stacktrace --no-daemon

      - store_artifacts:
          path: core/build/libs

      - store_artifacts:
          path: kotlin-dsl/build/libs

      - store_artifacts:
          path: extension/build/libs

      - run:
          name: Run tests
          command: PATH=`pwd`/cmake-3.14/bin:$PATH bash gradlew test --info --stacktrace --no-daemon

      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always

      - store_test_results:
          path: ~/junit
